Fix for
yyasun/Templator pull request #13
Opened 2023-02-02 19:53 UTC by nagasakinuclear

2023-02-02 21:51 UTC, nagasakinuclear commented on src/Templator/Templator.Logic/SourceFileGeneration/Contracts/IModuleFileGenerator.cs
> +        Task Generate(string path, ModuleFile module, TrieNode<ConfiguredTemplate> configuredTemplates);
TODO: pass forest of configurations into the ModuleFileGenerator

2023-02-02 21:51 UTC, nagasakinuclear commented on src/Templator/Templator.Logic/SourceFileGeneration/Contracts/IModuleGeneratorStrategy.cs
> +        Task Generate(ModuleFile module, string path, TrieNode<ConfiguredTemplate> configuredTemplates);
TODO: pass forest of configurations into the ModuleFileGenerator

2023-02-02 21:51 UTC, nagasakinuclear commented on src/Templator/Templator.Logic/SourceFileGeneration/TemplateFileContentGenerator.cs
> +        private readonly ITemplateOutputFileGenerator _templateOutputFileGenerator;
TODO: rename ITemplateOutputFileGenerator to ITemplateOutputGenerator

2023-02-02 21:51 UTC, nagasakinuclear commented on src/Templator/Templator.Logic/SourceFileGeneration/TemplateFileContentGenerator.cs
> +                // TODO: support multiple template extension names
// TODO: support multiple template extension names

                // TODO: support different file names

                // TODO: do this part in CSharpProjectGenerator and also remove projectName and path parametr

2023-02-02 21:51 UTC, nagasakinuclear commented on src/Templator/Templator.Logic/SourceFileGeneration/TemplateOutputFileGenerator.cs
> +            HandleNode(templateModel.TokenTrie[i], context, builder, templateModel);
TODO: remove template model from params. It exists in the context

2023-02-02 21:51 UTC, nagasakinuclear commented on src/Templator/Templator.Logic/TemplateRetrieverService.cs
> +    public class TemplateGraphBuilderService : ITemplateGraphBuilderService
TODO: rename to TemplateGraphBuilder

2023-02-04 14:53 UTC, yyasun requested changes

2023-02-04 14:53 UTC, yyasun commented on src/Templator/Templator.Domain/Models/TemplateElements/Structural/FileToGenerateModel.cs
> +        public string DefaultExtension { get; set; } = ".cs";
bruh?

2023-02-04 14:53 UTC, yyasun commented on src/Templator/Templator.Logic/SourceFileGeneration/FileCreator.cs
> +        public static async Task CreateFile(string path, string content)
please make thiss FileCreator Mockable

2023-02-04 14:53 UTC, yyasun commented on src/Templator/Templator.Logic/SourceFileGeneration/TemplateFileContentGenerator.cs
> +        public IEnumerable<TemplateFileContentGeneratorOutput> GenerateFileContent(TemplateModel templateModel, TrieNode<ConfiguredTemplate> configuredTemplateNode)
please rename GenerateFileContent to plural

2023-02-04 15:01 UTC, merged